server:
  port: 8075

spring:
  application:    name: business-web
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lanaya_dev?serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: 123456
  
eureka:
  instance:    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 10    service-url:
      defaultZone: http://localhost:8071/eureka/
    healthcheck:      enabled: true